[profile.default]
solc_version = "0.8.13"
src = "contracts"
test = "test"
script = "scripts"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 1000
evm_version = "london"
fs_permissions = [
  { access = "read-write", path = "./deployments.toml" }
]

[rpc_endpoints]
anvil   = "http://127.0.0.1:8545"
