version: "3.3"
services:
  development:
    image: ghcr.io/foundry-rs/foundry:stable
    entrypoint: ["anvil"]
    command:
      [
        "--host","0.0.0.0",
        "--port","8545",
        "--chain-id","5777",
        "--accounts","10",
        "--mnemonic","math razor capable expose worth grape metal sunset metal sudden usage scheme",
        "--gas-limit","1000000000",
        "--base-fee","0",
        "--balance","100000",
        "--block-time","10"
      ]
    ports:
      - "8545:8545"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-s", "http://127.0.0.1:8545", "-H", "Content-Type: application/json", "-d", "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"eth_blockNumber\",\"params\":[]}"]
      interval: 2s
      timeout: 1s
      retries: 30
  geth:
    build: ./geth
    ports:
      - 8545:8545
      - 8546:8546
