name: Forge Unit Tests

on:
  pull_request: {}
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "25"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          npm ci

      - name: Run unit tests
        run: npm test
